# Generated by Django 6.0.3 on 2026-03-20 18:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('contact', '0005_alter_empresa_options_contact_owner'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Empresa',
            new_name='Category',
        ),
        migrations.AlterModelOptions(
            name='category',
            options={'verbose_name': 'Categoria', 'verbose_name_plural': 'Categorias'},
        ),
        migrations.RenameField(
            model_name='contact',
            old_name='empresa',
            new_name='category',
        ),
    ]
