# Generated by Django 6.0.3 on 2026-03-30 14:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contact', '0006_rename_empresa_category_alter_category_options_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Asd',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('only_name', models.CharField(max_length=50)),
            ],
        ),
    ]
